version: '3.4'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:10501;http://+:10500
    ports:
      - "10500:10500"
      - "10501:10501"
