version: '3.8'

services:
  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Product
      - ASPNETCORE_URLS=https://+:10501;http://+:10500
    ports:
      - "65003:10500"
      - "65004:10501"
